### ISSUE TITLE
TypeInitializationException with NET 4.8 and WWF

### ISSUE THREAD

**Issue by Gebov** [microsoft/dotnet#1074]
I have this very strange issue where I receive a TypeInitializationException whenever the .net attempts to run the ModuleConstructor for the Microsoft.VisualBasic.Activities.Compieler.dll in a very specific scenario. 

## The scenario:

I have an OData batch request that sends a changeset (transactional request) to the server with 2 requests inside. The first request updates an item and passes successfully. The second requests invokes a xamlx file by loading it and calling the WorkflowApplication.Run() (from WWF). But then the second request fails with a TypeIntiializationException saying that the 
```"The type initializer for '<Module>' threw an exception." ```and the module being Microsoft.VisualBasic.Activities.Compiler.dll. 
The inner error being:
The C++ module failed to load while attempting to initialize the default appdomain.
The next inner error being:
Type 'Custom.CustomIdentity' in Assembly 'Custom, Version=...' is not marked as serializable.

We have a custom IPrincipal(CustomPrincipal and CustomIdentity classes) set in the current Thread that are used for authentication and authorization.

Once this module fails to initialize further requests for this batch request stay broken until we recycle the app pool.

**This was working fine with .net 4.7.2.**

The one thing that helped mitigate the problem was [this article](https://world.episerver.com/blogs/Svante-Seleborg/Dates/2011/10/The-type-initializer-for-Module-threw-an-exception/)

Wrapping our custom principal in a MarshalByRef object helps to avoid the problem. However I think there might be some breaking change introduced in the WWF as there were a lot of changes introduced with the .net[ 4.8 release](https://github.com/microsoft/dotnet-framework-early-access/blob/master/release-notes/NET48/dotnet-48-changes.md)

**Comment by sujayvsarma** [comment]
Is your `CustomIdentity` class marked as `Serializable` ?

**Comment by Gebov** [comment]
Then the bottom error transforms to "Could not load file or assembly 'Custom, Version=...' or one of its dependencies. The system cannot find the file specified"

**Comment by sujayvsarma** [comment]
Years ago, I implemented a CMS system with support for C#/VB and XAML workflows. It has been running code-untouched on 4.5 (what was originally used to write the code) through to 4.8. I am guessing your issue has something to do with how you are loading up your XAMLX. 

Could you post some code-extracts of how you are doing this part?

> The second requests invokes a xamlx file by loading it and calling the WorkflowApplication.Run() (from WWF)

Specifically which overload(s) of Assembly.Load are you using? And how are you instantiating the Activity? If it helps, here are some pieces from mine:

Assembly load
```
// CompilerOutputAssembly is a at the point with type Assembly
CompilerOutputAssembly = Assembly.Load(File.ReadAllBytes(primaryAssemblyPath));
```

Instantiation
```
System.Activities.Activity v4Activity = (System.Activities.Activity)workflowAssembly.CreateInstance(workflowClassName, true);
```

Also, since you mention you moved from 4.7.2 to 4.8, ensure that the `System.Activities` DLL reference is correct. I have had trouble in the early days of it loading one up from the wrong .NET FX.

**Comment by Gebov** [comment]
I checked the reference. It points to 4.8. If I compile my project against 4.7.2, but still have 4.8 installed, the issue is still reproducible. 

So my xamlx files are embedded resources and are loaded like so:
``` 
private static Activity LoadContentApprovalWorkflow(string workflowServiceVirtualPath)
{ 
     using (var stream = Abstractions.VirtualPath.VirtualFile.Open(workflowServiceVirtualPath))
               {
                    System.ServiceModel.Activities.WorkflowService service = (System.ServiceModel.Activities.WorkflowService)XamlServices.Load(stream);
                                sequence = (Sequence)service.Body;
                                return sequence;
                }
}
```

And the code that executes the worklfow:

```
var activity = WorkflowManager.LoadContentApprovalWorkflow(workflowUrl);

var evt = new ManualResetEvent(false);

var workflowApplication = new WorkflowApplication(activity)
{
	Completed = eventArgs => DisposeWorkflowThread(evt, requiresTransaction),
	Aborted = eventArgs => DisposeWorkflowThread(evt, requiresTransaction),
	OnUnhandledException = OnWorkflowUnhandledException

};

workflowApplication.Run(); // throws error here.
evt.WaitOne();

```

One interesting observation from the tests I've made is that if I run the second piece of code during application start-up before any batch request gets executed - everything works fine with subsequent batch requests.

It seems to me that some static variable initialization is failing somewhere along the execution of the batch request and then remains broken until app pool recycle. If however this static initialization is done before the batch request, everything works fine. Which led me to attempt to try the following code during app startup (runs the module initializer of the "Microsoft.VisualBasic.Activities.Compiler" assembly)

```
var assemblies = AppDomain.CurrentDomain.GetAssemblies();

            foreach (var assembly in assemblies)
            {
                if (assembly.FullName.StartsWith("Microsoft.VisualBasic.Activities.Compiler"))
                {
                    var modules = assembly.GetLoadedModules(false);
                    foreach (var module in modules)
                    {
                        RuntimeHelpers.RunModuleConstructor(module.ModuleHandle);
                    }
                }
            }
```

It did not help, but the interesting thing is that this code does not throw any errors during startup, but if I execute the batch request and achieve the above mentioned error, this same peace of code will throw the same error. This is one of the reasons I think some static variable initialization is failing somewhere.

**Comment by sujayvsarma** [comment]
Instrument and narrow it down? I don't see how anyone can give you further ideas on this...

**Comment by dasetser** [comment]
@Gebov Thanks for reporting this. I looked through the changes we made to Workflow in 4.8 and none of them stand out as something that would impact this scenario. It doesn't look like we changed Microsoft.VisualBasic.Activities.Compiler.dll or the places in the code where we're calling into it. 

It sounds like you are hitting a similar problem to what's described in the article you linked. In this case we're also calling into unmanaged code so your custom objects have to get serialized/marshaled. It makes sense that the same workaround works for you.

Unfortunately I'm not sure what we can do unless you can narrow down the cause of the difference in behavior. The error seems to be coming from the "Type 'Custom.CustomIdentity' in Assembly 'Custom, Version=...' is not marked as serializable." error, which turned into "The system cannot find the file specified" if you mark it as serializable. What was happening here when it was working? Was it able to find the assembly location for some reason but it's unable to now? Or did it lose permission to load from that location? Or was it able to serialize/marshal it but for some reason it can't with the new version? If you can understand how this marshaling or serialization was being handled in the working case we can investigate what changed about it to cause this behavior difference.

It sounds like you have a workaround to avoid the issue, which is good because then this shouldn't block you. It would be great if we can narrow down why the behavior is different so we can see if it's something we can fix.

**Comment by Gebov** [comment]
@dasetser Sorry for the late response. I can only speculate that the main reason is the type was not serialized before and is being serialized with the new version. The only reproducible scenario that I have found working is that installing .net 4.8 will cause the exception on the same application that was running fine with .net 4.7.2. It would be very helpful if I could debug the .net assemblies somehow (the debug version of them).  This way I think I can narrow it down. I tried using reference source, but going through the optimized code did not help that much.

**Comment by dasetser** [comment]
@Gebov To my knowledge since this issue is for the .NET Framework all you can do is follow the instructions listed in https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-debug-dotnet-framework-source?view=vs-2019 as well as disabling JIT optimization as specified in https://docs.microsoft.com/en-us/visualstudio/debugger/jit-optimization-and-debugging?view=vs-2019.

Since this is not an open source product, If you need more assistance than that to identify what's going on here I would suggest looking into opening a Microsoft support case for this issue so we can work more closely with you on how to narrow this down and get it fixed. I apologize that I can't be more helpful, but right now we don't have enough information to tell what is causing this.

**Comment by Alois-xx** [comment]
You could try to debug it with dnSpy. See https://aloiskraus.wordpress.com/2019/09/08/how-net-4-8-can-break-your-application/ how to drill deep into .NET Framework with full locals.

**Comment by Gebov** [comment]
So we finally got to the bottom of this case. There was a check in the .net code if the current user (on the current thread) is not serializable throw an exception. I cannot remember the exact details, but it seemed that our custom iprincipal was somehow lost from the thread. We set it at the proper place and everything worked
