### ISSUE TITLE
Existence of SizeToContent in XAML breaks Loaded Event of window

### ISSUE THREAD

**Issue by Seikilos** [Microsoft/dotnet#429]
[SizeToContentProblem.zip](https://github.com/Microsoft/dotnet/files/1087679/SizeToContentProblem.zip)
We've noticed a very strange behaviour that is reproducible in VS 2017 and with dotnet 4.6.2.
The attached repro case consist of a window with a button that opens another window. In this window there is an interactivity trigger (`TestWindow.xaml`) that should create a message box and a console entry.
However due to the presence of `SizeToContent="Height"` in the very same xaml, dotnet does only emit the console write line from the callback set in the code behind (`Loaded="TestWindow_OnLoaded"`) but ignores the callback that should be executed in `TestWindowViewModel`.

If the `SizeToContent` attribute is removed in `TestWindow.xaml`, then the expected message box is displayed and the second console output (after the message box) is generated, see the image below for the correct version when SizeToContent is commented out.

![grafik](https://user-images.githubusercontent.com/1260908/27329430-d2640c46-55b5-11e7-8046-069605e151ae.png)

**Comment by richlander** [comment]
I sent this to the WPF team. Thanks for reporting.

**Comment by richlander** [comment]
For Microsoft folks: I created Microsoft-internal VSTS bug 460315 to track this.

**Comment by Bodewes** [comment]
Als see https://stackoverflow.com/questions/32627331/eventtocommand-for-loaded-event-not-working-as-expected-if-window-sizetocontent for another case and a workaround.

**Comment by SirRufo** [comment]
I tested with Win10 1709.16299.19, VS2017 v15.5.0 Preview 2.0, .net v4.7.02556 and there is no such issue

**Comment by richlander** [comment]
Great!

**Comment by AridTag** [comment]
We recently upgraded our WPF projects to target .NET 4.7.1 so I tried to remove the workaround mentioned in the StackOverflow post linked by @Bodewes as @SirRufo mentioned he was not able to reproduce the issue on .NET 4.7.1

It still did not execute the command. 
Just to confirm that I didn't screw up, I removed the SizeToContent="WidthAndHeight" and tried again. This time the command was executed as you would expect.

Windows 10 1709.16299.248
VS2017 15.5.4

**Comment by krs500** [comment]
I can confirm that this issue hasn't been fixed. Please find the attached example, **targeting .NET 4.7.1**, which demonstrates the problem very clearly. The command in the event trigger starts working as soon as the SizeToContent="WidthAndHeight" is removed.

[SizeToContentProblem_NET471.zip](https://github.com/Microsoft/dotnet/files/1978128/SizeToContentProblem_NET471.zip)

**Comment by sonhai1710** [comment]
is it fixed yet? until june 19th 2019

**Comment by GreatFireWall** [comment]
Still not fix if SizeToContent="Width" .

VS2019 16.4.4
.NET Framework 4.7.2

**Comment by NorbertHuethmayr** [comment]
This also happens on VS 2019 and .Net 4.8 - Any workarounds/recommendations?

**Comment by XuanNghiemNguyen** [comment]
I also have this problem with vs 2019 and .Net 4.8.

**Comment by 349516385** [comment]
VS2022 17.6.0 
.Net7  
It is still not fixed.

**Comment by RossMetacraft** [comment]
Confirmed issue is still present in .NET 8.

**Comment by SirRufo** [comment]
> Confirmed issue is still present in .NET 8.

Are you using [Microsoft.Xaml.Behaviors.Wpf](https://www.nuget.org/packages/Microsoft.Xaml.Behaviors.Wpf/) to use the latest version?

Documentation is [here](https://devblogs.microsoft.com/dotnet/open-sourcing-xaml-behaviors-for-wpf/)

**Comment by RossMetacraft** [comment]
> Are you using [Microsoft.Xaml.Behaviors.Wpf](https://www.nuget.org/packages/Microsoft.Xaml.Behaviors.Wpf/) to use the latest version?

Yes, my application uses v1.1.135, which is the latest version currently.

**Comment by RossMetacraft** [comment]
Here's a simple repro app using .NET 8.

[WpfLoadedEventTest.zip](https://github.com/user-attachments/files/18969587/WpfLoadedEventTest.zip)

I noticed your repro app uses the community MVVM toolkit. I wonder if it does something as a workaround for this issue? My repro app does not use any packages other than Microsoft.Xaml.Behaviors.Wpf.

**Comment by SirRufo** [comment]
It happens only for the Window on Application Startup. Creating a new instance of MainWindow and showing will work as expected.

So the error from OP is solved but there is more on Startup

**Comment by RossMetacraft** [comment]
Agreed, it works properly for new instances of MainWindow, or for a secondary window that is opened from the main window. So the bug still exists in certain circumstances.

**Comment by SirRufo** [comment]
Well there is even a workaround for that
```c#
public partial class App : Application
{
    protected override void OnStartup( StartupEventArgs e )
    {
        // The first created Window will become App.MainWindow
        var main = new MainWindow()
        {
            DataContext = new MainViewModel(),
        };

        // create not visible at all dummy window
        var dummy = new Window()
        {
            ShowInTaskbar = false,
            Height = 1,
            Width = 1,
            WindowStyle = WindowStyle.None,
            AllowsTransparency = true,
            Background = Brushes.Transparent,
        };
        // show it and will 'eat' the bug
        dummy.Show();
        // close dummy
        dummy.Close();

        // show the real main window
        main.Show();
    }
}
```

**Comment by RossMetacraft** [comment]
Looks like the bug still exists in some circumstances even for secondary windows that are created and shown later after the application has already started. I still have the problem in my application when a window is shown as a modal dialog using `ShowDialog()`. This window uses a custom window base class, so maybe that has something to do with it. The problem goes away if I remove the `SizeToContent` attribute. I'll see if I can figure out why it still happens with this secondary window.
