### ISSUE TITLE
Assembly didn't be loaded lead to Xaml missing

### ISSUE THREAD

**Issue by TruePluto** [Microsoft/dotnet#548]
I make a desktop application with WPF. my solution includes three projects. One Application (A). and two assemblies (B) and (C).  assembly B referenced assembly C. and was referenced by Application A. but Appication A didn't referenced C direcetly.
Assembly C including a control and have some styles in the file Generic.xaml.
Assembly B including a window (xaml) and have a reference assembly C's Generic.xaml. but any behind code didn't use the classes in the assembly C.  classes in assembly C just used for datatemplate in B's xaml.
The solution can be compile but will lead to crack. report said that missing assembly  C or  the Generic.xaml in assembly C.
but if i add a line code in B  such as "  private Cclass obj=null " it will be ok.
I think Assembly B didn't load the Assembly C without code reference
So Xaml don't found the code 

[WpfApp2.zip](https://github.com/Microsoft/dotnet/files/1436144/WpfApp2.zip)

in the project B Window1.xaml.cs have code.

        //*********************************************
        // remove the following line will lead the applition to cracked
        // but I actually do not need these lines
        //*********************************************
        private DragThumb dragThumb = null;

can represent the issue.

Doesn't  Xaml load assembly automatically.

**Comment by richlander** [comment]
Good question.

My understanding from your code/example is that the C# compiler sees the DragThumb reference and then understands that you have a static reference on the C project. If that reference isn't there, then the resource dictionary entry in C isn't found because (it appears) that the Xaml compiler doesn't add a static reference to the C project.

Is that right, @unniravindranathan? Do you have any guidance to provide?

**Comment by TruePluto** [comment]
@richlander, I don't know the mechanism actually, but from the present I think you are right. The resources are loaded by C# code not by Xaml. if a resource just be needed as a tamplate, C# code will not reference it and load it.
thank you.

**Comment by richlander** [comment]
I suspect that the XAML compiler expects that you have a static reference to dependent assemblies and that it isn't otherwise capable of reporting those references to MSBuild in order to get the assembly to be copied in the bin directory.

You have a very easy workaround, so I suggest you just use it and move on. Is that OK?

**Comment by TruePluto** [comment]
Thank you. I think application A doesn't or needn't to know the existing of assemble C. so it doesn't need have a static reference to assemble C. (in my solution i know should static reference c, but if it's a part of thrid package, I won't know which one I should reference.) 
but of course as your mention. I'm working on a easy workaround. so I can use it and move on. but it's totally a fraustration.
and thank you @richlander for your attention again.

**Comment by richlander** [comment]
Do you have an example of a third party package where this happens?

**Comment by richlander** [comment]
It appears like this topic has been resolved.

**Comment by TruePluto** [comment]
In fact, I just let the **private DragThumb dragThumb = null;** inside my codes,
I just can't find any third partner assmebles which lead to this problem.
The problem isn't solved. @richlander
