### ISSUE TITLE
After installing 4.7.1, IIS AppPool stops with "Cannot read configuration file"

### ISSUE THREAD

**Issue by geeeyetee** [Microsoft/dotnet#572]
After installing .Net Framework v4.7.1 on Windows 10-- either on its own or via the Fall Creators Update-- some IIS application pools persistently stop immediately after they are started. The following event is logged.

```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
 <System>
  <Provider Name="Microsoft-Windows-IIS-W3SVC-WP" Guid="{670080D9-742A-4187-8D16-41143D1290BD}" EventSourceName="W3SVC-WP" /> 
  <EventID Qualifiers="49152">2307</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="[EVENT TIME]" /> 
  <EventRecordID>[EVENT RECORD ID]</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>[COMPUTER NAME]</Computer> 
  <Security /> 
 </System>
 <EventData>
  <Data Name="ApplicationPool">[APP POOL NAME]</Data> 
  <Data Name="ConfigException">Cannot read configuration file</Data> 
  <Data Name="FileName">\\?\<EMPTY></Data> 
  <Data Name="LineNumber">0</Data> 
  <Binary>02000000</Binary> 
 </EventData>
</Event>
```

The following workaround, from [this answer](https://stackoverflow.com/a/47309481/704808) to the Stack Overflow question [Cannot read configuration file ' trying to read configuration data from file '\\?\<EMPTY>', line number '0'](https://stackoverflow.com/questions/47309480/cannot-read-configuration-file-trying-to-read-configuration-data-from-file), resolves the problem:

>  1. Go to the drive your IIS is installed on, eg. `C:\inetpub\temp\appPools\`
>  2. Delete the directory (or virtual directory) with the same name as your app pool.
>  3. Recycle/Start your app pool again.

**Comment by HongGit** [comment]
This is a known issue with Fall Creators Update, see [this KB](https://support.microsoft.com/en-us/help/4050891/error-http-503-and-was-event-5189-from-web-applications-on-windows-10).

**Comment by geeeyetee** [comment]
So it is! Thank you for pointing that out. I have confirmed that my System log contains event WAS 5189, described in the KB article, concurrent with event shown above from my Application log, Microsoft-Windows-IIS-W3SVC-WP 2307. Adding the latter event to the KB article might make it more discoverable. Also, a commenter on the Stack Overflow answer linked above indicated the problem was triggered for him by installing .Net Framework v4.7.1. I do not know whether the commenter did so without installing the Fall Creators Update, but this may be worth investigating.

**Comment by HongGit** [comment]
@shirhatti can you please comment?

**Comment by shirhatti** [comment]
@geeeyetee Installing .NET Framework 4.7.1 is just a red herring in your case. We've already fixed the Windows setup logic that resulted in these malformed symlinks that get created during your OS upgrade. Unfortunately, if you upgraded to Windows 10 Fall Creators Update prior to our fix going out, you'll hit this issue.

**Comment by alex-kazantsev** [comment]
@shirhatti
I had got the same issue after installing Fall Creators Update 3 days ago. The issue was NOT fixed.
